dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=armor setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: Vi+cXlau8F6Tu+6XzeJZUZWZ6lz1RRm0r4ty0UpAYNfWxI4Xv3sZQ6w3biNrBZRNF8gHGj3NGcVOgV62i7eR0TOFefRsukHL9blro1OFMDQxJ/L4x4zuaU38iUPxKo7HYtVR8YGUz0mUzZKl/36AR7MxInsKa5vtqpRQMZQXzbM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
